#!/usr/bin/env bash

ssh ubuntu@54.173.13.99 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDD34v/ZOV3rqgi2MQ5Ekd8oKcGFEg+w2o4WaFoTVZQVGvCbDZBlxCmWgnlQyXeKEzdQ4Tv/pE55cCWiAJrtsDXmvE9p5Yn8D77U5IA+X0b/TTka2AjTQ2Ar6X/9Z7VWlJIURtIZHQraTns/N/x/Y7E/SUm/cm3O91dL3GmD317rtaJtuEq2z7qWd4vU9s6vZAyqCREYgoG2mHqH4qBN5JukYUGa3+skcG17jvLYVnoHSAXOhLmm3v7fhu9dYJBGiqiOBzGcRmGVKfkIi34/35r+0rDcufsYyTSY3s3Lfr4Fe88cfRR/RgGM1Z1MOKul91MqrpKMSmrlxKLpMM98ZyJ3Pz0ZOvpwFE1eAntAnxZHY8RWGxJHlnSEyHmAtWyJX1fqTCem7EGFJQYop1Xkor1/fSJ3Q1MEZm/8wqPT+M+8/rTNmde2N3uVHUljBy2b4OOqcu4Vb/CK5VgTnxRx3pcIcpzvZzIqNQ1L6xVtNkbjEmI0EgpK7o05TnTnyS5RS88oBqs5N4hboVwTJaX+7qaGuQzXZKAhAsBJQjMppnnBEzC7a4tMDUKQYNJ9ipGTtuJNvaIX/4nZnWFP51mmluKf86j/NRFrCotmgLC2Ijfe1SJwuYIT/uCqIzlrJTmXBpWG7jNuNs7P0OSM9nOZM8Ur86IULRq9sUE1cQApW5FuQ== root@10a805a54a82 >> ~/.ssh/authorized_keys
